services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg43217890fdsa
      POSTGRES_DB: tododb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d tododb"]
      interval: 5s
      retries: 5
  test-db:
    image: postgres:17
    environment:
      POSTGRES_USER: pgtest
      POSTGRES_PASSWORD: pgtestfdsa
      POSTGRES_DB: todo_test
    ports:
      - "127.0.0.1:5443:5432"
    tmpfs:
      - /var/lib/postgres/data

volumes:
  pgdata:
