"""add due_dat, created_at

Revision ID: f5a74ae8f279
Revises: f2187aa7ec7c
Create Date: 2026-08-02 20:42:18.908848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a74ae8f279'
down_revision: Union[str, Sequence[str], None] = 'f2187aa7ec7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###
